api: 2

core: 8.x

projects:
  drupal:
    version: 8.7.x
    patch:
      text-processed-fix: https://www.drupal.org/files/issues/2018-05-15/text-processed-fix.patch
      3020001-3: https://www.drupal.org/files/issues/2018-12-12/3020001-3.patch
  key_value: 1.x
  key: 1.x
  encrypt: 3.x
  conflict:
    type: module
    download:
      type: git
      branch: 8.x-1.x
      url: "https://github.com/drupaldeploy/drupal-conflict.git"
  multiversion:
    type: module
    download:
      type: git
      branch: 8.x-2.x
      url: "https://github.com/dickolsson/drupal-multiversion.git"
